routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'Admin\AdminAccountController@profile')->name('profile');

        Route::post('profile/save', 'Admin\AdminAccountController@profile_save')->name('profile.save');

        Route::post('change/password', 'Admin\AdminAccountController@change_password')->name('change.password');

        Route::get('/', 'Admin\AdminRevenueController@main_dashboard')->name('dashboard');
        
        // Users CRUD Operations

        Route::get('users', 'Admin\AdminUserController@users_index')->name('users.index');

        Route::get('users/create', 'Admin\AdminUserController@users_create')->name('users.create');

        Route::get('users/edit', 'Admin\AdminUserController@users_edit')->name('users.edit');

        Route::post('users/save', 'Admin\AdminUserController@users_save')->name('users.save');

        Route::get('users/view', 'Admin\AdminUserController@users_view')->name('users.view');

        Route::get('users/delete', 'Admin\AdminUserController@users_delete')->name('users.delete');

        Route::get('users/status', 'Admin\AdminUserController@users_status')->name('users.status');

        Route::get('users/verify', 'Admin\AdminUserController@users_verify_status')->name('users.verify');

        Route::get('users/verify_badge', 'Admin\AdminUserController@users_verify_badge_status')->name('users.verify_badge');

        Route::get('users/excel','Admin\AdminUserController@users_excel')->name('users.excel');

        Route::post('/users/bulk_action', 'Admin\AdminUserController@users_bulk_action')->name('users.bulk_action');

        Route::get('/users/billing_accounts','Admin\AdminUserController@billing_accounts_index')->name('users.billing_accounts');
        
        Route::get('/users/content_creator_upgrade','Admin\AdminUserController@content_creator_upgrade')->name('users.content_creator_upgrade');

        Route::get('/users/featured_seller_upgrade','Admin\AdminUserController@featured_seller_upgrade')->name('users.featured_seller_upgrade');

        Route::get('users/carts', 'Admin\AdminUserController@carts_list')->name('users.carts');

        Route::get('users/remove', 'Admin\AdminUserController@carts_remove')->name('users.carts.remove');

        //user documents 

        Route::get('user-documents', 'Admin\AdminUserController@user_documents_index')->name('user_documents.index');

        Route::get('user-document', 'Admin\AdminUserController@user_documents_view')->name('user_documents.view');
        
        Route::get('user-documents/verify', 'Admin\AdminUserController@user_documents_verify')->name('user_documents.verify');

        Route::get('users/upgrade_account', 'Admin\AdminUserController@user_upgrade_account')->name('users.upgrade_account');

        //followers
         Route::get('followers' , 'Admin\AdminUserController@user_followers')->name('user_followers');

        Route::get('followings', 'Admin\AdminUserController@user_followings')->name('user_followings');

        //user products CRUD Operations

        Route::get('products', 'Admin\AdminProductController@user_products_index')->name('user_products.index');

        Route::get('products/create', 'Admin\AdminProductController@user_products_create')->name('user_products.create');

        Route::get('products/edit', 'Admin\AdminProductController@user_products_edit')->name('user_products.edit');

        Route::post('products/save', 'Admin\AdminProductController@user_products_save')->name('user_products.save');

        Route::get('products/view', 'Admin\AdminProductController@user_products_view')->name('user_products.view');

        Route::get('products/delete', 'Admin\AdminProductController@user_products_delete')->name('user_products.delete');

        Route::get('products/status', 'Admin\AdminProductController@user_products_status')->name('user_products.status');

        Route::get('products/dashboard', 'Admin\AdminProductController@user_products_dashboard')->name('user_products.dashboard');

        Route::get('order_products','Admin\AdminProductController@order_products')->name('order_products');

        // Document CRUD Operations

        Route::get('documents', 'Admin\AdminLookupController@documents_index')->name('documents.index');

        Route::get('documents/create', 'Admin\AdminLookupController@documents_create')->name('documents.create');

        Route::get('documents/edit', 'Admin\AdminLookupController@documents_edit')->name('documents.edit');

        Route::post('documents/save', 'Admin\AdminLookupController@documents_save')->name('documents.save');

        Route::get('documents/view', 'Admin\AdminLookupController@documents_view')->name('documents.view');

        Route::get('documents/delete', 'Admin\AdminLookupController@documents_delete')->name('documents.delete');

        Route::get('documents/status', 'Admin\AdminLookupController@documents_status')->name('documents.status');

        // Documents end

        //orders start

        Route::get('orders' , 'Admin\AdminOrderController@orders_index')->name('orders.index');

        Route::get('orders/view', 'Admin\AdminOrderController@orders_view')->name('orders.view');

        Route::get('order/payments','Admin\AdminRevenueController@order_payments')->name('order.payments');

        Route::get('order/payments/view','Admin\AdminRevenueController@order_payments_view')->name('order.payments.view');

        //orders end

        //delivery address routes start

        Route::get('delivery_address' , 'Admin\AdminOrderController@delivery_address_index')->name('delivery_address.index');

        Route::get('delivery_address/delete', 'Admin\AdminOrderController@delivery_address_delete')->name('delivery_address.delete');

        Route::get('delivery_address/view', 'Admin\AdminOrderController@delivery_address_view')->name('delivery_address.view');

        //delivery address routes end
        
        //user wallet route start

        Route::get('user_wallets' , 'Admin\AdminRevenueController@user_wallets_index')->name('user_wallets.index');

        Route::get('user_wallets/view', 'Admin\AdminRevenueController@user_wallets_view')->name('user_wallets.view');

        Route::get('user_wallet_payments/view', 'Admin\AdminRevenueController@user_wallet_payments_view')->name('user_wallet_payments.view');

        //user wallet route end

        //revenue dashboard start

        Route::get('revenues/dashboard','Admin\AdminRevenueController@revenues_dashboard')->name('revenues.dashboard');

        //revenue dashboard end

        Route::post('categories/get_sub_categories', 'Admin\AdminLookupController@get_sub_categories')->name('get_sub_categories');

        //categories end

        //sub_categories start
        Route::get('sub_categories', 'Admin\AdminLookupController@sub_categories_index')->name('sub_categories.index');

        Route::get('sub_categories/create', 'Admin\AdminLookupController@sub_categories_create')->name('sub_categories.create');

        Route::get('sub_categories/edit', 'Admin\AdminLookupController@sub_categories_edit')->name('sub_categories.edit');

        Route::post('sub_categories/save', 'Admin\AdminLookupController@sub_categories_save')->name('sub_categories.save');

        Route::get('sub_categories/view', 'Admin\AdminLookupController@sub_categories_view')->name('sub_categories.view');

        Route::get('sub_categories/delete', 'Admin\AdminLookupController@sub_categories_delete')->name('sub_categories.delete');

        Route::get('sub_categories/status', 'Admin\AdminLookupController@sub_categories_status')->name('sub_categories.status');



        //sub_categories end

        // CC withdrawals start

        Route::get('user_withdrawals','Admin\AdminRevenueController@user_withdrawals')->name('user_withdrawals');

        Route::get('user_withdrawals/paynow','Admin\AdminRevenueController@user_withdrawals_paynow')->name('user_withdrawals.paynow');

        Route::get('user_withdrawals/reject','Admin\AdminRevenueController@user_withdrawals_reject')->name('user_withdrawals.reject');

         Route::get('user_withdrawals/view','Admin\AdminRevenueController@user_withdrawals_view')->name('user_withdrawals.view');

        // CC withdrawals end

        //inventory route start

        Route::get('product_inventories/index' , 'Admin\AdminRevenueController@product_inventories_index')->name('product_inventories.index');

        Route::get('product_inventories/view', 'Admin\AdminRevenueController@product_inventories_view')->name('product_inventories.view');

        //inventory route end

        //faq CRUD
        Route::get('faqs', 'Admin\AdminLookupController@faqs_index')->name('faqs.index');

        Route::get('faqs/create', 'Admin\AdminLookupController@faqs_create')->name('faqs.create');

        Route::get('faqs/edit', 'Admin\AdminLookupController@faqs_edit')->name('faqs.edit');

        Route::post('faqs/save', 'Admin\AdminLookupController@faqs_save')->name('faqs.save');

        Route::get('faqs/view', 'Admin\AdminLookupController@faqs_view')->name('faqs.view');

        Route::get('faqs/delete', 'Admin\AdminLookupController@faqs_delete')->name('faqs.delete');

        Route::get('faqs/status', 'Admin\AdminLookupController@faqs_status')->name('faqs.status');
        //faq end


        // Static pages start

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

Route::get('settings_generate_json', 'ApplicationController@settings_generate_json')->name('settings_generate_json');

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
   protected $hidden = ['deleted_at', 'id', 'unique_id'];

	protected $appends = ['document_id', 'document_unique_id'];

    public function getDocumentIdAttribute() {

        return $this->id;
    }

    public function getDocumentUniqueIdAttribute() {

        return $this->unique_id;
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeCommonResponse($query) {

        return $query;
    
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeApproved($query) {

        return $query->where('documents.status', APPROVED);
    
    }

    public static function boot() {

        parent::boot();

        static::creating(function ($model) {
            $model->attributes['unique_id'] = "KV"."-".uniqid();
        });

        static::created(function($model) {

            $model->attributes['unique_id'] = "KV"."-".$model->attributes['id']."-".uniqid();

            $model->save();
        
        });

    }
}

resources/views/admin/users/documents/_search.blade.php
<form method="GET" action="{{route('admin.user_documents.index')}}">

<div class="row">

    <div class="col-xs-12 col-sm-12 col-lg-4 col-md-6 resp-mrg-btm-md">
        @if(Request::has('search_key'))
        <p class="text-muted">Search results for <b>{{Request::get('search_key')}}</b></p>
        @endif
    </div>

    <div class="col-xs-12 col-sm-12 col-lg-6 mx-auto col-md-12">

        <div class="input-group form-margin-left-sm">

            <input type="text" class="form-control" name="search_key" value="{{Request::get('search_key')??''}}" placeholder="{{tr('users_search_placeholder')}}"> <span class="input-group-btn">
                &nbsp

                <button type="submit" class="btn btn-default reset-btn">
                    <i class="fa fa-search" aria-hidden="true"></i>
                </button>

                <a href="{{route('admin.user_documents.index')}}" class="btn btn-default reset-btn">
                    <i class="fa fa-eraser" aria-hidden="true"></i>
                </a>

            </span>

        </div>

    </div>

</div>

</form>

<br>

resources/views/admin/users/documents/index.blade.php
@extends('layouts.admin')

@section('title', tr('users'))

@if($page == 'users-documents')

    @section('content-header', tr('verification_documents'))

@else

    @section('content-header', tr('users'))

@endif

@section('breadcrumb')


<li class="breadcrumb-item active">
    <a href="{{route('admin.users.index')}}">{{ tr('users') }}</a>
</li>

<li class="breadcrumb-item">{{tr('verification_documents')}}</li>

@endsection

@section('content')

<section class="content">

    <div class="row">

        <div class="col-12">

        <div class="card">

            <div class="card-header border-bottom border-gray">

                <h4 class="card-title">{{tr('verification_documents')}}</h4>

            </div>
            <div class="box-body">
                    <div class="callout bg-pale-secondary">
                        <h4>{{tr('notes')}}</h4>
                        <p>
                            </p><ul>
                                <li>
                                    {{tr('doument_verificatin_notes')}}
                                </li>
                            </ul>
                        <p></p>
                    </div>
                </div>
            <div class="box box-outline-info">
                <div class="box-body">
                    <div class="table-responsive">

                        @include('admin.users.documents._search')

                        <table id="dataTable" class="table table-bordered table-striped display nowrap margin-top-10">

                            <thead>
                                <tr>
                                    <th>{{tr('s_no')}}</th>
                                    <th>{{tr('username')}}</th>
                                    <th>{{tr('email_mobile')}}</th>
                                    <th>{{tr('no_of_documents')}}</th>
                                    <th>{{tr('status')}}</th>
                                    <th>{{tr('action')}}</th>
                                </tr>
                            </thead>

                            <tbody>

                                @foreach($users as $i => $user)

                                <tr>
                                    <td>{{$i+$users->firstItem()}}</td>

                                    <td>
                                        <a href="{{route('admin.users.view' , ['user_id' => $user->id])}}">
                                            {{ $user->name  ?? "-" }}
                                        </a>
                                    </td>

                                    <td>
                                        {{$user->email}}
                                        <span>
                                            <h6>{{$user->mobile?: tr('not_available')}}</h6>
                                        </span>
                                    </td>

                                    <td>
                                        <a class="btn btn-outline-pink" href="{{route('admin.user_documents.view', ['user_id' => $user->id])}}">
                                            {{$user->userDocuments->count()}}
                                        </a>
                                    </td>

                                    <td>
                                        @if($user->status == USER_DOCUMENT_APPROVED)
                                        <span class="btn btn-success btn-sm">{{tr('approved')}}</span>
                                        @else
                                        <span class="btn btn-warning btn-sm">{{tr('declined')}}</span>

                                        @endif

                                    </td>

                                    <td>

                                        @if($user->documents_count > 0)

                                        @if($user->is_document_verified != USER_DOCUMENT_APPROVED)

                                        <a class="btn btn-success" href="{{route('admin.user_documents.verify', ['user_id' => $user->user_id,'status'=>USER_DOCUMENT_APPROVED])}}" onclick="return confirm(&quot;{{tr('user_document_verify_confirmation')}}&quot;);">
                                            {{tr('verify')}}
                                        </a>

                                        @else

                                        <a class="btn btn-success" href="{{route('admin.user_documents.verify', ['user_id' => $user->user_id,'status'=>USER_DOCUMENT_DECLINED])}}" onclick="return confirm(&quot;{{tr('user_document_verify_confirmation')}}&quot;);">
                                            {{tr('decline')}}
                                        </a>

                                        @endif

                                        <a class="btn btn-warning" href="{{route('admin.user_documents.view', ['user_id' => $user->id])}}">
                                            {{ tr('view_all_documents') }}
                                        </a>
                                        @else

                                        <a class="btn btn-success" href="#" onClick="alert(&quot;{{tr('user_documents_empty')}}&quot;)">
                                            {{tr('verify')}}
                                        </a>
                                        @endif

                                    </td>

                                </tr>

                                @endforeach

                            </tbody>

                        </table>

                        <div class="pull-right" id="paglink">{{ $users->appends(request()->input())->links() }}</div>


                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->

@endsection

resources/views/admin/users/documents/view.blade.php
@extends('layouts.admin') 

@section('title', tr('users')) 

@section('content-header', tr('users')) 

@section('breadcrumb')

<li class="breadcrumb-item">
    <a href="{{ route('admin.users.index') }}">{{ tr('users') }}</a>
</li>

<li class="breadcrumb-item active">{{ tr('documents') }}</li>

@endsection 

@section('content')

<section class="content">

    <div class="row">

        <div class="col-12">

            <p>{{tr('user_documents_verify_notes')}}</p>

            <div class="card user-document-verify-sec">

                <div class="card-header border-bottom border-gray">

                    <h4 class="card-title">{{ tr('verification_documents') }} - <a class="" href="{{route('admin.users.view',['user_id'=> $user->id])}}">{{ $user->name ?? tr('n_a')}}</a></h4>

                    <div class="heading-elements">

                        @if($user->is_document_verified != USER_DOCUMENT_APPROVED)

                            @if($user_documents->count() > 0)

                                <a class="btn btn-success" href="{{route('admin.user_documents.verify', ['user_id' => $user->user_id,'status'=>USER_DOCUMENT_APPROVED])}}" onclick="return confirm(&quot;{{tr('user_document_verify_confirmation')}}&quot;);"><i class="icon-badge"></i> {{tr('verify')}}
                                </a>

                            @endif

                            @if($user_documents->count() <= 0)

                                <button class="btn btn-info text-capitalize" disabled>{{tr('user_documents_waiting_upload')}}</button>

                            @endif

                        @else

                            <a class="btn btn-success" href="#"><i class="icon-badge"></i> {{tr('verified')}}
                            </a>

                        @endif


                    </div>
                    
                </div>

                <div class="card-content collapse show">

                    <div class="card-body card-dashboard">

                    <table id="dataTable" class="table table-bordered table-striped display nowrap margin-top-10">

                            <thead>
                                <tr>
                                    <th>{{ tr('s_no') }}</th>
                                    <th>{{ tr('document_name') }}</th>
                                    <th>{{ tr('updated_on') }}</th>
                                    <th>{{ tr('action') }}</th>
                                </tr>
                            </thead>

                            <tbody>
                                        
                                @foreach($user_documents as $i => $document)

                                <tr>

                                    <td>{{ $i+$user_documents->firstItem() }}</td>

                                    <td>
                                        <a href="{{ route('admin.documents.view',['document_id' => $document->document_id ]) }}">{{$document->document->name ?? "-"}} </a>
                                    </td>

                                    <td>
                                        {{common_date($document->updated_at, Auth::guard('admin')->user()->timezone)}}
                                    </td>

                                    <td>
                                        <a href='{{ $document->document_file ? $document->document_file :"#"}}' target="_blank">
                                            <span class="btn btn-warning btn-large">{{ tr('view') }}</span>
                                        </a>
                                    </td>

                                </tr>

                                @endforeach
                            </tbody>

                        </table>
                        <div class="pull-right" id="paglink">{{ $user_documents->appends(request()->input())->links() }}</div>
                    </div>
                
                </div>
            </div>
        </div>
    </div>

</section>

@endsection