routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'Admin\AdminAccountController@profile')->name('profile');

        Route::post('profile/save', 'Admin\AdminAccountController@profile_save')->name('profile.save');

        Route::post('change/password', 'Admin\AdminAccountController@change_password')->name('change.password');

        Route::get('/', 'Admin\AdminRevenueController@main_dashboard')->name('dashboard');
        
        // Users CRUD Operations

        Route::get('users', 'Admin\AdminUserController@users_index')->name('users.index');

        Route::get('users/create', 'Admin\AdminUserController@users_create')->name('users.create');

        Route::get('users/edit', 'Admin\AdminUserController@users_edit')->name('users.edit');

        Route::post('users/save', 'Admin\AdminUserController@users_save')->name('users.save');

        Route::get('users/view', 'Admin\AdminUserController@users_view')->name('users.view');

        Route::get('users/delete', 'Admin\AdminUserController@users_delete')->name('users.delete');

        Route::get('users/status', 'Admin\AdminUserController@users_status')->name('users.status');

        Route::get('users/verify', 'Admin\AdminUserController@users_verify_status')->name('users.verify');

        Route::get('users/verify_badge', 'Admin\AdminUserController@users_verify_badge_status')->name('users.verify_badge');

        Route::get('users/excel','Admin\AdminUserController@users_excel')->name('users.excel');

        Route::post('/users/bulk_action', 'Admin\AdminUserController@users_bulk_action')->name('users.bulk_action');

        Route::get('/users/billing_accounts','Admin\AdminUserController@billing_accounts_index')->name('users.billing_accounts');
        
        Route::get('/users/content_creator_upgrade','Admin\AdminUserController@content_creator_upgrade')->name('users.content_creator_upgrade');

        Route::get('/users/featured_seller_upgrade','Admin\AdminUserController@featured_seller_upgrade')->name('users.featured_seller_upgrade');

        Route::get('users/carts', 'Admin\AdminUserController@carts_list')->name('users.carts');

        Route::get('users/remove', 'Admin\AdminUserController@carts_remove')->name('users.carts.remove');

        //user documents 

        Route::get('user-documents', 'Admin\AdminUserController@user_documents_index')->name('user_documents.index');

        Route::get('user-document', 'Admin\AdminUserController@user_documents_view')->name('user_documents.view');
        
        Route::get('user-documents/verify', 'Admin\AdminUserController@user_documents_verify')->name('user_documents.verify');

        Route::get('users/upgrade_account', 'Admin\AdminUserController@user_upgrade_account')->name('users.upgrade_account');

        //followers
         Route::get('followers' , 'Admin\AdminUserController@user_followers')->name('user_followers');

        Route::get('followings', 'Admin\AdminUserController@user_followings')->name('user_followings');

        //user products CRUD Operations

        Route::get('products', 'Admin\AdminProductController@user_products_index')->name('user_products.index');

        Route::get('products/create', 'Admin\AdminProductController@user_products_create')->name('user_products.create');

        Route::get('products/edit', 'Admin\AdminProductController@user_products_edit')->name('user_products.edit');

        Route::post('products/save', 'Admin\AdminProductController@user_products_save')->name('user_products.save');

        Route::get('products/view', 'Admin\AdminProductController@user_products_view')->name('user_products.view');

        Route::get('products/delete', 'Admin\AdminProductController@user_products_delete')->name('user_products.delete');

        Route::get('products/status', 'Admin\AdminProductController@user_products_status')->name('user_products.status');

        Route::get('products/dashboard', 'Admin\AdminProductController@user_products_dashboard')->name('user_products.dashboard');

        Route::get('order_products','Admin\AdminProductController@order_products')->name('order_products');

        // Document CRUD Operations

        Route::get('documents', 'Admin\AdminLookupController@documents_index')->name('documents.index');

        Route::get('documents/create', 'Admin\AdminLookupController@documents_create')->name('documents.create');

        Route::get('documents/edit', 'Admin\AdminLookupController@documents_edit')->name('documents.edit');

        Route::post('documents/save', 'Admin\AdminLookupController@documents_save')->name('documents.save');

        Route::get('documents/view', 'Admin\AdminLookupController@documents_view')->name('documents.view');

        Route::get('documents/delete', 'Admin\AdminLookupController@documents_delete')->name('documents.delete');

        Route::get('documents/status', 'Admin\AdminLookupController@documents_status')->name('documents.status');

        // Documents end

        //orders start

        Route::get('orders' , 'Admin\AdminOrderController@orders_index')->name('orders.index');

        Route::get('orders/view', 'Admin\AdminOrderController@orders_view')->name('orders.view');

        Route::get('order/payments','Admin\AdminRevenueController@order_payments')->name('order.payments');

        Route::get('order/payments/view','Admin\AdminRevenueController@order_payments_view')->name('order.payments.view');

        //orders end

        //delivery address routes start

        Route::get('delivery_address' , 'Admin\AdminOrderController@delivery_address_index')->name('delivery_address.index');

        Route::get('delivery_address/delete', 'Admin\AdminOrderController@delivery_address_delete')->name('delivery_address.delete');

        Route::get('delivery_address/view', 'Admin\AdminOrderController@delivery_address_view')->name('delivery_address.view');

        //delivery address routes end
        
        //user wallet route start

        Route::get('user_wallets' , 'Admin\AdminRevenueController@user_wallets_index')->name('user_wallets.index');

        Route::get('user_wallets/view', 'Admin\AdminRevenueController@user_wallets_view')->name('user_wallets.view');

        Route::get('user_wallet_payments/view', 'Admin\AdminRevenueController@user_wallet_payments_view')->name('user_wallet_payments.view');

        //user wallet route end

        //revenue dashboard start

        Route::get('revenues/dashboard','Admin\AdminRevenueController@revenues_dashboard')->name('revenues.dashboard');

        //revenue dashboard end

        Route::post('categories/get_sub_categories', 'Admin\AdminLookupController@get_sub_categories')->name('get_sub_categories');

        //categories end

        //sub_categories start
        Route::get('sub_categories', 'Admin\AdminLookupController@sub_categories_index')->name('sub_categories.index');

        Route::get('sub_categories/create', 'Admin\AdminLookupController@sub_categories_create')->name('sub_categories.create');

        Route::get('sub_categories/edit', 'Admin\AdminLookupController@sub_categories_edit')->name('sub_categories.edit');

        Route::post('sub_categories/save', 'Admin\AdminLookupController@sub_categories_save')->name('sub_categories.save');

        Route::get('sub_categories/view', 'Admin\AdminLookupController@sub_categories_view')->name('sub_categories.view');

        Route::get('sub_categories/delete', 'Admin\AdminLookupController@sub_categories_delete')->name('sub_categories.delete');

        Route::get('sub_categories/status', 'Admin\AdminLookupController@sub_categories_status')->name('sub_categories.status');



        //sub_categories end

        // CC withdrawals start

        Route::get('user_withdrawals','Admin\AdminRevenueController@user_withdrawals')->name('user_withdrawals');

        Route::get('user_withdrawals/paynow','Admin\AdminRevenueController@user_withdrawals_paynow')->name('user_withdrawals.paynow');

        Route::get('user_withdrawals/reject','Admin\AdminRevenueController@user_withdrawals_reject')->name('user_withdrawals.reject');

         Route::get('user_withdrawals/view','Admin\AdminRevenueController@user_withdrawals_view')->name('user_withdrawals.view');

        // CC withdrawals end

        //inventory route start

        Route::get('product_inventories/index' , 'Admin\AdminRevenueController@product_inventories_index')->name('product_inventories.index');

        Route::get('product_inventories/view', 'Admin\AdminRevenueController@product_inventories_view')->name('product_inventories.view');

        //inventory route end

        //faq CRUD
        Route::get('faqs', 'Admin\AdminLookupController@faqs_index')->name('faqs.index');

        Route::get('faqs/create', 'Admin\AdminLookupController@faqs_create')->name('faqs.create');

        Route::get('faqs/edit', 'Admin\AdminLookupController@faqs_edit')->name('faqs.edit');

        Route::post('faqs/save', 'Admin\AdminLookupController@faqs_save')->name('faqs.save');

        Route::get('faqs/view', 'Admin\AdminLookupController@faqs_view')->name('faqs.view');

        Route::get('faqs/delete', 'Admin\AdminLookupController@faqs_delete')->name('faqs.delete');

        Route::get('faqs/status', 'Admin\AdminLookupController@faqs_status')->name('faqs.status');
        //faq end


        // Static pages start

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

Route::get('settings_generate_json', 'ApplicationController@settings_generate_json')->name('settings_generate_json');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
	/**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = ['id'];

    protected $appends = ['category_id'];

    public function getCategoryIdAttribute() {

        return $this->id;
    }

    public function subCategories() {

        return $this->hasMany(SubCategory::class,'category_id');
    }

    public function userProducts() {

        return $this->hasMany(UserProduct::class,'category_id');
    }

    public function liveVideos() {

        return $this->hasMany(LiveVideo::class,'category_id');
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeCommonResponse($query) {

        return $query;
    
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeApproved($query) {

        return $query->where('categories.status', APPROVED);

    }

    public static function boot() {

        parent::boot();

        static::creating(function ($model) {

            $model->attributes['unique_id'] = routefreestring(strtolower($model->attributes['name']));

        });

        static::created(function($model) {

            $model->attributes['unique_id'] = routefreestring(strtolower($model->attributes['name']));

            $model->save();
        
        });

        static::updating(function ($model) {

            $model->attributes['unique_id'] = routefreestring(strtolower($model->attributes['name']));
            
        });

        static::deleting(function ($model){

            $model->subCategories()->delete();

            $model->userProducts()->delete();
        });

    }
}

resources/views/admin/categories/_search.blade.php
<form class="col-6 row pull-right" action="{{route('admin.categories.index')}}" method="GET" role="search">
    <div class="input-group">
        <input type="text" class="form-control" name="search_key"  value="{{Request::get('search_key')??''}}"
        placeholder="{{tr('categories_search_placeholder')}}" required> 
        <span class="input-group-btn">
            &nbsp
            <button type="submit" class="btn btn-default">
                <i class="fa fa-search" aria-hidden="true"></i>
            </button>
            <a href="{{route('admin.categories.index')}}" class="btn btn-default reset-btn">
                <span class=""> <i class="fa fa-eraser" aria-hidden="true"></i>
                </span>
            </a>
        </span>
    </div>
</form>

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('title', tr('add_category'))

@section('content-header', tr('product_categories'))

@section('breadcrumb')

    <li class="breadcrumb-item"><a href="{{route('admin.categories.index')}}">{{tr('product_categories')}}</a></li>

    <li class="breadcrumb-item active">{{tr('add_category')}}</a></li>

@endsection

@section('content')

    @include('admin.categories._form')

@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('title', tr('edit_category'))

@section('content-header', tr('product_categories'))

@section('breadcrumb')

    <li class="breadcrumb-item"><a href="{{route('admin.categories.index')}}">{{tr('product_categories')}}</a></li>

    <li class="breadcrumb-item active">{{tr('edit_category')}}</a></li>

@endsection

@section('content')

    @include('admin.categories._form')

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin') 

@section('content-header', tr('categories')) 

@section('breadcrumb')

<li class="breadcrumb-item">
    <a href="{{route('admin.categories.index')}}">{{tr('categories')}}</a>
</li>

<li class="breadcrumb-item active">{{ tr('view_categories') }}</li>

@endsection 

@section('content')

<section class="content">

    <div class="row">

        <div class="col-12">

            <div class="card">

                <div class="card-header border-bottom border-gray">

                    <h4 class="card-title">{{ tr('view_categories') }}</h4>

                    <div class="heading-elements">
                        <a href="{{ route('admin.categories.create') }}" class="btn btn-primary"><i class="ft-plus icon-left"></i>{{ tr('add_category') }}</a>
                    </div>
                    
                </div>
                <div class="box-body">
                    <div class="callout bg-pale-secondary">
                        <h4>{{tr('notes')}}</h4>
                        <p>
                            </p><ul>
                                <li>
                                    {{tr('product_category_notes')}}
                                </li>
                            </ul>
                        <p></p>
                    </div>
                </div>

                <div class="box box-outline-info">

                    <div class="box-body">

                        @include('admin.categories._search')
                        
                        <div class="table-responsive">

                            <table id="dataTable" class="table table-bordered table-striped display nowrap margin-top-10">
                            
                                <thead>
                                    <tr>
                                        <th>{{ tr('s_no') }}</th>
                                        <th>{{ tr('category_name') }}</th>
                                        <th>{{tr('sub_category_count')}}</th>
                                        <th>{{tr('total_products_count')}}</th>
                                        <th>{{ tr('picture') }}</th>
                                        <th>{{ tr('status') }}</th>
                                        <th>{{ tr('action') }}</th>
                                    </tr>
                                </thead>
                               
                                <tbody>

                                    @foreach($categories as $i => $category)
                                    <tr>
                                        <td>{{ $i+$categories->firstItem() }}</td>

                                        <td>
                                            <a href="{{  route('admin.categories.view' , ['category_id' => $category->id] )  }}">
                                            {{ $category->name ?: tr('n_a')}}
                                            </a>
                                        </td>

                                        <td>
                                        <a href="{{route('admin.sub_categories.index',['category_id' => $category->id])}}">{{$category->sub_categories_count ? : 0}}
                                       </a>
                                    </td>

                                        <td>
                                            <a href="{{route('admin.user_products.index',['category_id' => $category->id])}}">
                                            {{ $category->user_products_count ? : 0}}
                                            </a>
                                        </td>

                                        <td><img src="{{$category->picture ?: asset('placeholder.jpg')}}" class="category-image"></td>
                                        
                                        <td>
                                            @if($category->status == APPROVED)

                                                <span class="btn btn-success btn-sm">{{ tr('approved') }}</span> 
                                            @else

                                                <span class="btn btn-warning btn-sm">{{ tr('declined') }}</span> 
                                            @endif
                                        </td>

                                        <td>
                                        
                                            <div class="btn-group" role="group">

                                                <button class="btn btn-outline-primary dropdown-toggle dropdown-menu-right" id="btnGroupDrop1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="ft-settings icon-left"></i> {{ tr('action') }}</button>

                                                <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">

                                                    <a class="dropdown-item" href="{{ route('admin.categories.view', ['category_id' => $category->id] ) }}">&nbsp;{{ tr('view') }}</a> 

                                                    @if(Setting::get('is_demo_control_enabled') == YES)

                                                        <a class="dropdown-item" href="javascript:void(0)">&nbsp;{{ tr('edit') }}</a>

                                                        <a class="dropdown-item" href="javascript:void(0)">&nbsp;{{ tr('delete') }}</a> 

                                                    @else

                                                        <a class="dropdown-item" href="{{ route('admin.categories.edit', ['category_id' => $category->id] ) }}">&nbsp;{{ tr('edit') }}</a>

                                                        <a class="dropdown-item" onclick="return confirm(&quot;{{ tr('category_delete_confirmation' , $category->name) }}&quot;);" href="{{ route('admin.categories.delete', ['category_id' => $category->id] ) }}">&nbsp;{{ tr('delete') }}</a>

                                                    @endif

                                                    @if($category->status == APPROVED)

                                                        <a class="dropdown-item" href="{{  route('admin.categories.status' , ['category_id' => $category->id] )  }}" onclick="return confirm(&quot;{{ $category->name }} - {{ tr('category_decline_confirmation') }}&quot;);">&nbsp;{{ tr('decline') }}
                                                    </a> 

                                                    @else

                                                        <a class="dropdown-item" href="{{ route('admin.categories.status' , ['category_id' => $category->id] ) }}">&nbsp;{{ tr('approve') }}</a> 

                                                    @endif
                                                    <a class="dropdown-item" href="{{route('admin.user_products.index',['category_id' => $category->id])}}">&nbsp;{{ tr('total_products') }}</a> 

                                                    <a class="dropdown-item" href="{{route('admin.sub_categories.index',['category_id' => $category->id])}}">&nbsp;{{ tr('sub_categories') }}</a> 

                                                    <a class="dropdown-item" href="{{ route('admin.sub_categories.create') }}">&nbsp;{{ tr('add_sub_categories') }}</a> 
                                                </div>

                                            </div>

                                        </td>

                                    </tr>

                                    @endforeach

                                </tbody>
                        
                            </table>

                            <div class="pull-right" id="paglink">{{ $categories->appends(request()->input())->links() }}</div>
                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</section>

@endsection

resources/views/admin/categories/view.blade.php
@extends('layouts.admin')

@section('title', tr('product_categories'))

@section('content-header', tr('product_categories'))

@section('breadcrumb')

    <li class="breadcrumb-item"><a href="{{route('admin.categories.index')}}">{{tr('product_categories')}}</a>
    </li>
    <li class="breadcrumb-item active">{{tr('view_categories')}}</a>
    </li>

@endsection

@section('content')

<section class="content">

        <div class="row">

            <div class="col-xl-12 col-lg-12">

                <div class="card user-profile-view-sec">

                    <div class="card-header border-bottom border-gray">

                        <h4 class="card-title">{{tr('view_category')}}</h4>

                    </div>

                    <div class="card-content">

                        <div class="col-md-12">

                            <div class="card profile-with-cover">

                                <div class="media profil-cover-details w-100">

                                    <div class="media-left pl-2 pt-2">

                                        <a class="profile-image">
                                             <img src="{{ $category->picture ?: asset('placeholder.jpg')}}" alt="{{ $category->name}}" class="img-thumbnail img-fluid img-border height-100"
                                        alt="Card image">
                                        </a>

                                    </div>

                                   
                                </div>

                            
                            </div>
                        
                        </div>

                        <hr>
                        <div class="user-view-padding">
                            <div class="row"> 

                                <div class=" col-xl-6 col-lg-6 col-md-12">
                                    <div class="table-responsive">

                                        <table class="table table-xl mb-0">
                                            <tr >
                                                <th>{{tr('category_name')}}</th>
                                                <td>{{$category->name ?: tr('n_a')}}</td>
                                            </tr>

                                            <tr>
                                                
                                                <th>{{tr('sub_category_count')}}</th>
                                                <td><a href="{{route('admin.sub_categories.index',['category_id' => $category->id])}}">{{$category->subCategories->count() ?? tr('n_a')}}</a></td>

                                            </tr>

                                            <tr>
                                                
                                                <th>{{tr('user_products')}}</th>
                                                <td><a href="{{route('admin.user_products.index',['category_id' => $category->id])}}">{{$category->UserProducts->count() ?? tr('n_a')}}</a></td>

                                            </tr>

                                            <tr>
                                                <th>{{tr('status')}}</th>
                                                <td>
                                                    @if($category->status == APPROVED) 

                                                        <span class="badge badge-success">{{tr('approved')}}</span>

                                                    @else
                                                        <span class="badge badge-danger">{{tr('declined')}}</span>

                                                    @endif
                                                </td>
                                            </tr>

                                            <tr>
                                                <th>{{tr('created_at')}} </th>
                                                <td>{{common_date($category->created_at , Auth::guard('admin')->user()->timezone)}}</td>
                                            </tr>

                                            <tr>
                                                <th>{{tr('updated_at')}} </th>
                                                <td>{{common_date($category->updated_at , Auth::guard('admin')->user()->timezone)}}</td>
                                            </tr> 

                                            <tr>
                                                <th>{{tr('description')}}</th>
                                                <td>{{Str::limit($category->description , 20 ?: tr('n_a'))}}</td>
                                            </tr> 
                                        </table>

                                    </div>
                                </div>

                                <div class="col-xl-6 col-lg-6 col-md-12">

                                    <div class="px-2 resp-marg-top-xs">

                                        <div class="card-title">{{tr('action')}}</div>

                                        <div class="row">

                                            @if(Setting::get('is_demo_control_enabled') == YES)

                                            <div class="col-xl-6 col-lg-6 col-md-12">

                                                <a class="btn btn-secondary btn-block btn-min-width mr-1 mb-1 " href="javascript:void(0)"> &nbsp;{{tr('edit')}}</a>

                                            </div>

                                            <div class="col-xl-6 col-lg-6 col-md-12">

                                                <a class="btn btn-danger btn-block btn-min-width mr-1 mb-1" href="javascript:void(0)">&nbsp;{{tr('delete')}}</a>

                                            </div>


                                            @else

                                            <div class="col-xl-6 col-lg-6 col-md-12">

                                                <a class="btn btn-secondary btn-block btn-min-width mr-1 mb-1 " href="{{route('admin.categories.edit', ['category_id'=>$category->id] )}}"> &nbsp;{{tr('edit')}}</a>

                                            </div>

                                            <div class="col-xl-6 col-lg-6 col-md-12">

                                                <a class="btn btn-danger btn-block btn-min-width mr-1 mb-1" onclick="return confirm(&quot;{{tr('user_delete_confirmation' , $category->name)}}&quot;);" href="{{route('admin.categories.delete', ['category_id'=> $category->id] )}}">&nbsp;{{tr('delete')}}</a>

                                            </div>

                                            @endif

                                            <div class="col-xl-6 col-lg-6 col-md-12">

                                                 @if($category->status == APPROVED)
                                                     <a class="btn btn-warning btn-block btn-min-width mr-1 mb-1" href="{{route('admin.categories.status' ,['category_id'=> $category->id] )}}" onclick="return confirm(&quot;{{$category->name}} - {{tr('category_decline_confirmation')}}&quot;);">&nbsp;{{tr('decline')}} </a> 
                                                @else

                                                    <a  class="btn btn-success btn-block btn-min-width mr-1 mb-1" href="{{route('admin.categories.status' , ['category_id'=> $category->id] )}}">&nbsp;{{tr('approve')}}</a> 
                                                @endif

                                            </div>

                                            <div class="col-xl-6 col-lg-6 col-md-12">

                                                <a class="btn btn-info btn-block btn-min-width mr-1 mb-1 " href="{{route('admin.user_products.index', ['category_id'=>$category->id] )}}"> &nbsp;{{tr('total_products')}}</a>

                                            </div>

                                            <div class="col-xl-6 col-lg-6 col-md-12">

                                                <a class="btn btn-success btn-block btn-min-width mr-1 mb-1 " href="{{route('admin.sub_categories.index',['category_id' => $category->id])}}"> &nbsp;{{tr('sub_category')}}</a>

                                            </div>



                                        </div>

                                    </div>

                                </div>
                        
                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

</section>


@endsection

@section('scripts')

@endsection