routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'Admin\AdminAccountController@profile')->name('profile');

        Route::post('profile/save', 'Admin\AdminAccountController@profile_save')->name('profile.save');

        Route::post('change/password', 'Admin\AdminAccountController@change_password')->name('change.password');

        Route::get('/', 'Admin\AdminRevenueController@main_dashboard')->name('dashboard');
        
        // Users CRUD Operations

        Route::get('users', 'Admin\AdminUserController@users_index')->name('users.index');

        Route::get('users/create', 'Admin\AdminUserController@users_create')->name('users.create');

        Route::get('users/edit', 'Admin\AdminUserController@users_edit')->name('users.edit');

        Route::post('users/save', 'Admin\AdminUserController@users_save')->name('users.save');

        Route::get('users/view', 'Admin\AdminUserController@users_view')->name('users.view');

        Route::get('users/delete', 'Admin\AdminUserController@users_delete')->name('users.delete');

        Route::get('users/status', 'Admin\AdminUserController@users_status')->name('users.status');

        Route::get('users/verify', 'Admin\AdminUserController@users_verify_status')->name('users.verify');

        Route::get('users/verify_badge', 'Admin\AdminUserController@users_verify_badge_status')->name('users.verify_badge');

        Route::get('users/excel','Admin\AdminUserController@users_excel')->name('users.excel');

        Route::post('/users/bulk_action', 'Admin\AdminUserController@users_bulk_action')->name('users.bulk_action');

        Route::get('/users/billing_accounts','Admin\AdminUserController@billing_accounts_index')->name('users.billing_accounts');
        
        Route::get('/users/content_creator_upgrade','Admin\AdminUserController@content_creator_upgrade')->name('users.content_creator_upgrade');

        Route::get('/users/featured_seller_upgrade','Admin\AdminUserController@featured_seller_upgrade')->name('users.featured_seller_upgrade');

        Route::get('users/carts', 'Admin\AdminUserController@carts_list')->name('users.carts');

        Route::get('users/remove', 'Admin\AdminUserController@carts_remove')->name('users.carts.remove');

        //user documents 

        Route::get('user-documents', 'Admin\AdminUserController@user_documents_index')->name('user_documents.index');

        Route::get('user-document', 'Admin\AdminUserController@user_documents_view')->name('user_documents.view');
        
        Route::get('user-documents/verify', 'Admin\AdminUserController@user_documents_verify')->name('user_documents.verify');

        Route::get('users/upgrade_account', 'Admin\AdminUserController@user_upgrade_account')->name('users.upgrade_account');

        //followers
         Route::get('followers' , 'Admin\AdminUserController@user_followers')->name('user_followers');

        Route::get('followings', 'Admin\AdminUserController@user_followings')->name('user_followings');

        //user products CRUD Operations

        Route::get('products', 'Admin\AdminProductController@user_products_index')->name('user_products.index');

        Route::get('products/create', 'Admin\AdminProductController@user_products_create')->name('user_products.create');

        Route::get('products/edit', 'Admin\AdminProductController@user_products_edit')->name('user_products.edit');

        Route::post('products/save', 'Admin\AdminProductController@user_products_save')->name('user_products.save');

        Route::get('products/view', 'Admin\AdminProductController@user_products_view')->name('user_products.view');

        Route::get('products/delete', 'Admin\AdminProductController@user_products_delete')->name('user_products.delete');

        Route::get('products/status', 'Admin\AdminProductController@user_products_status')->name('user_products.status');

        Route::get('products/dashboard', 'Admin\AdminProductController@user_products_dashboard')->name('user_products.dashboard');

        Route::get('order_products','Admin\AdminProductController@order_products')->name('order_products');

        // Document CRUD Operations

        Route::get('documents', 'Admin\AdminLookupController@documents_index')->name('documents.index');

        Route::get('documents/create', 'Admin\AdminLookupController@documents_create')->name('documents.create');

        Route::get('documents/edit', 'Admin\AdminLookupController@documents_edit')->name('documents.edit');

        Route::post('documents/save', 'Admin\AdminLookupController@documents_save')->name('documents.save');

        Route::get('documents/view', 'Admin\AdminLookupController@documents_view')->name('documents.view');

        Route::get('documents/delete', 'Admin\AdminLookupController@documents_delete')->name('documents.delete');

        Route::get('documents/status', 'Admin\AdminLookupController@documents_status')->name('documents.status');

        // Documents end

        //orders start

        Route::get('orders' , 'Admin\AdminOrderController@orders_index')->name('orders.index');

        Route::get('orders/view', 'Admin\AdminOrderController@orders_view')->name('orders.view');

        Route::get('order/payments','Admin\AdminRevenueController@order_payments')->name('order.payments');

        Route::get('order/payments/view','Admin\AdminRevenueController@order_payments_view')->name('order.payments.view');

        //orders end

        //delivery address routes start

        Route::get('delivery_address' , 'Admin\AdminOrderController@delivery_address_index')->name('delivery_address.index');

        Route::get('delivery_address/delete', 'Admin\AdminOrderController@delivery_address_delete')->name('delivery_address.delete');

        Route::get('delivery_address/view', 'Admin\AdminOrderController@delivery_address_view')->name('delivery_address.view');

        //delivery address routes end
        
        //user wallet route start

        Route::get('user_wallets' , 'Admin\AdminRevenueController@user_wallets_index')->name('user_wallets.index');

        Route::get('user_wallets/view', 'Admin\AdminRevenueController@user_wallets_view')->name('user_wallets.view');

        Route::get('user_wallet_payments/view', 'Admin\AdminRevenueController@user_wallet_payments_view')->name('user_wallet_payments.view');

        //user wallet route end

        //revenue dashboard start

        Route::get('revenues/dashboard','Admin\AdminRevenueController@revenues_dashboard')->name('revenues.dashboard');

        //revenue dashboard end

        Route::post('categories/get_sub_categories', 'Admin\AdminLookupController@get_sub_categories')->name('get_sub_categories');

        //categories end

        //sub_categories start
        Route::get('sub_categories', 'Admin\AdminLookupController@sub_categories_index')->name('sub_categories.index');

        Route::get('sub_categories/create', 'Admin\AdminLookupController@sub_categories_create')->name('sub_categories.create');

        Route::get('sub_categories/edit', 'Admin\AdminLookupController@sub_categories_edit')->name('sub_categories.edit');

        Route::post('sub_categories/save', 'Admin\AdminLookupController@sub_categories_save')->name('sub_categories.save');

        Route::get('sub_categories/view', 'Admin\AdminLookupController@sub_categories_view')->name('sub_categories.view');

        Route::get('sub_categories/delete', 'Admin\AdminLookupController@sub_categories_delete')->name('sub_categories.delete');

        Route::get('sub_categories/status', 'Admin\AdminLookupController@sub_categories_status')->name('sub_categories.status');



        //sub_categories end

        // CC withdrawals start

        Route::get('user_withdrawals','Admin\AdminRevenueController@user_withdrawals')->name('user_withdrawals');

        Route::get('user_withdrawals/paynow','Admin\AdminRevenueController@user_withdrawals_paynow')->name('user_withdrawals.paynow');

        Route::get('user_withdrawals/reject','Admin\AdminRevenueController@user_withdrawals_reject')->name('user_withdrawals.reject');

         Route::get('user_withdrawals/view','Admin\AdminRevenueController@user_withdrawals_view')->name('user_withdrawals.view');

        // CC withdrawals end

        //inventory route start

        Route::get('product_inventories/index' , 'Admin\AdminRevenueController@product_inventories_index')->name('product_inventories.index');

        Route::get('product_inventories/view', 'Admin\AdminRevenueController@product_inventories_view')->name('product_inventories.view');

        //inventory route end

        //faq CRUD
        Route::get('faqs', 'Admin\AdminLookupController@faqs_index')->name('faqs.index');

        Route::get('faqs/create', 'Admin\AdminLookupController@faqs_create')->name('faqs.create');

        Route::get('faqs/edit', 'Admin\AdminLookupController@faqs_edit')->name('faqs.edit');

        Route::post('faqs/save', 'Admin\AdminLookupController@faqs_save')->name('faqs.save');

        Route::get('faqs/view', 'Admin\AdminLookupController@faqs_view')->name('faqs.view');

        Route::get('faqs/delete', 'Admin\AdminLookupController@faqs_delete')->name('faqs.delete');

        Route::get('faqs/status', 'Admin\AdminLookupController@faqs_status')->name('faqs.status');
        //faq end


        // Static pages start

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

Route::get('settings_generate_json', 'ApplicationController@settings_generate_json')->name('settings_generate_json');

resources/views/admin/delivery_address/_search.blade.php
  <form method="GET" action="{{route('admin.delivery_address.index')}}" class="form-bottom">

    <div class="row">

        <input type="hidden" id="user_id" name="user_id" value="{{Request::get('user_id') ?? ''}}">

        <div class="col-xs-12 col-sm-12 col-lg-6 col-md-12"></div>

        <div class="col-xs-12 col-sm-12 col-lg-6 col-md-12">

            <div class="input-group">
               
                <input type="text" class="form-control" name="search_key"
                placeholder="{{tr('delivery_search_placeholder')}}"> <span class="input-group-btn">
                &nbsp

                <button type="submit" class="btn btn-default">
                   <a href=""><i class="fa fa-search" aria-hidden="true"></i></a>
                </button>
                
                <button class="btn btn-default"><a  href="{{route('admin.delivery_address.index')}}"><i class="fa fa-eraser" aria-hidden="true"></i></button>
                </a>
                   
                </span>

            </div>
            
        </div>

    </div>

</form>

resources/views/admin/delivery_address/index.blade.php
@extends('layouts.admin') 

@section('title', tr('delivery_address')) 

@section('content-header', tr('delivery_address')) 

@section('breadcrumb')

<li class="breadcrumb-item active">
    <a href="{{route('admin.users.index')}}">{{ tr('users') }}</a>
</li>
<li class="breadcrumb-item">{{ tr('delivery_address') }}</li>

@endsection 

@section('content')

<section class="content">

    <div class="row">

        <div class="col-12">

            <div class="card">

                <div class="card-header border-bottom border-gray">

                    <h4 class="card-title">{{ tr('delivery_address') }} @if($user)- <a href="{{ route('admin.users.view',['user_id'=>$user->id]) }}">{{$user->name}}</a> @endif
                    
                    </h4>
                    
                </div>


                <div class="box box-outline-info">

                    <div class="box-body">

                        <div class="table-responsive">

                            @include('admin.delivery_address._search')
                            
                            <table id="dataTable" class="table table-bordered table-striped display nowrap margin-top-10">
                                
                                <thead>
                                    <tr>
                                        <th>{{ tr('s_no') }}</th>
                                        <th>{{ tr('user') }}</th>
                                        <th>{{ tr('name') }}</th>
                                        <th>{{ tr('delivery_address') }}</th>
                                        <th>{{ tr('pincode') }}</th>
                                        <th>{{ tr('state')}}</th>
                                        <th>{{ tr('landmark')}}</th>
                                        <th>{{ tr('status') }}</th>
                                        <th>{{ tr('action') }}</th>
                                    </tr>
                                </thead>
                               
                                <tbody>

                                    @foreach($delivery_addresses as $i => $delivery_address_details)

                                    <tr>
                                        <td>{{ $i + $delivery_addresses->firstItem() }}</td>

                                        <td>
                                            <a href="{{  route('admin.users.view' , ['user_id' => $delivery_address_details->user_id] )  }}">
                                            {{ $delivery_address_details->user->name ?? "-" }}
                                            </a>
                                        </td>

                                        <td>{{ $delivery_address_details->name ?? "-" }}</td>

                                        <td>{{Str::limit($delivery_address_details->address ,15 ?? "-") }}</td>


                                        <td>
                                            {{ $delivery_address_details->pincode }}
                                        </td>

                                        <td>{{ $delivery_address_details->state }}</td>

                                        <td>{{ $delivery_address_details->landmark }}
                                        </td>

                                        <td>
                                            @if($delivery_address_details->status == APPROVED)

                                            <span class="btn btn-success btn-sm">{{ tr('approved') }}</span> @else

                                            <span class="btn btn-warning btn-sm">{{ tr('declined') }}</span> @endif
                                        </td>

                                        <td>
                                        
                                            <div class="btn-group" role="group">

                                                <button class="btn btn-outline-primary dropdown-toggle dropdown-menu-right" id="btnGroupDrop1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="ft-settings icon-left"></i> {{ tr('action') }}</button>

                                                <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">

                                                    <a class="dropdown-item" href="{{ route('admin.delivery_address.view', ['delivery_address_id' => $delivery_address_details->id] ) }}">&nbsp;{{ tr('view') }}</a> 

                                                    @if(Setting::get('is_demo_control_enabled') == YES)

                                            
                                                        <a class="dropdown-item" href="javascript:void(0)">&nbsp;{{ tr('delete') }}</a> 

                                                    @else

                                                        <a class="dropdown-item" onclick="return confirm(&quot;{{ tr('delivery_address_delete_confirmation' , $delivery_address_details->name) }}&quot;);" href="{{ route('admin.delivery_address.delete', ['delivery_address_id' => $delivery_address_details->id,'page'=>request()->input('page')] ) }}">&nbsp;{{ tr('delete') }}</a>

                                                    @endif

                                                </div>

                                            </div>


                                        </td>

                                    </tr>

                                    @endforeach

                                </tbody>
                            
                            </table>

                            <div class="pull-right" id="paglink">{{ $delivery_addresses->appends(request()->input())->links() }}</div>

                        </div>

                    </div>
                </div>

            </div>

        </div>

    </div>

</section>

@endsection

resources/views/admin/delivery_address/view.blade.php
@extends('layouts.admin') 

@section('title', tr('delivery_address')) 

@section('content-header', tr('delivery_address')) 

@section('breadcrumb')


<li class="breadcrumb-item active">{{tr('delivery_address')}}</li>

@endsection 

@section('content')

<section id="configuration">

    <div class="row">

        <div class="col-12">

            <div class="card">

                <div class="card-header border-bottom border-gray">

                    <h4 class="card-title">{{ tr('delivery_address_details') }}&nbsp;
                       <a class="pull-right btn btn-sm btn-danger rounded" onclick="return confirm(&quot;{{ tr('delivery_address_delete_confirmation' , $delivery_address_details->name) }}&quot;);" href="{{ route('admin.delivery_address.delete', ['delivery_address_id' => $delivery_address_details->id] ) }}"> <i class="fa fa-trash"></i></a>
                    </h4>
                    
                </div>

                <div class="card-content collapse show">

                    <div class="card-body card-dashboard">
                                    
                        <div class="row">

                            <div class="col-md-6">

                                <div class="list-group">

                                    <a href="{{ route('admin.users.view', ['user_id' => $delivery_address_details->user_id] ) }}" class="list-group-item">

                                        <div class="media">
                                      
                                            <div class="media-body w-100">
                                                <h6 class="media-heading mb-0">{{$delivery_address_details->user->name ?? "-"}}</h6>
                                                <p class="font-small-2 mb-0 text-muted">{{tr('delivery_address_user')}}</p>
                                            </div>

                                        </div>

                                    </a>

                                    <a href="javascript:void(0)" class="list-group-item">

                                        <div class="media">
                                      
                                            <div class="media-body w-100">
                                                <h6 class="media-heading mb-0">{{$delivery_address_details->name}}</h6>
                                                <p class="font-small-2 mb-0 text-muted">{{tr('name')}}</p>
                                            </div>

                                        </div>
                                        
                                    </a>

                                    <a href="javascript:void(0)" class="list-group-item">

                                        <div class="media">
                                      
                                            <div class="media-body w-100">
                                                <h6 class="media-heading mb-0">{{$delivery_address_details->contact_number}}</h6>
                                                <p class="font-small-2 mb-0 text-muted">{{tr('contact_number')}}</p>
                                            </div>

                                        </div>
                                        
                                    </a>

                                     <a href="javascript:void(0)" class="list-group-item">

                                        <div class="media">
                                      
                                            <div class="media-body w-100">
                                                <h6 class="media-heading mb-0"> @if($delivery_address_details->status == APPROVED)

                                                    <span class="btn btn-success btn-sm">{{ tr('approved') }}</span> @else

                                                    <span class="btn btn-warning btn-sm">{{ tr('declined') }}</span> @endif
                                                </h6>
                                                <p class="font-small-2 mb-0 text-muted">{{tr('status')}}</p>
                                            </div>

                                        </div>
                                        
                                    </a>

                                    <a href="javascript:void(0)" class="list-group-item">

                                        <div class="media">
                                      
                                            <div class="media-body w-100">
                                                <h6 class="media-heading mb-0">{{$delivery_address_details->landmark}}</h6>
                                                <p class="font-small-2 mb-0 text-muted">{{tr('landmark')}}</p>
                                            </div>

                                        </div>
                                        
                                    </a>
                                 
                                </div>

                            </div>

                            <div class="col-md-6">

                                <div class="list-group">

                                    <a href="javascript:void(0)" class="list-group-item">

                                        <div class="media">
                                      
                                            <div class="media-body w-100">
                                                <h6 class="media-heading mb-0">{{$delivery_address_details->address}}</h6>
                                                <p class="font-small-2 mb-0 text-muted">{{tr('address')}}</p>
                                            </div>

                                        </div>

                                    </a>

                                    <a href="javascript:void(0)" class="list-group-item">

                                        <div class="media">
                                      
                                            <div class="media-body w-100">
                                                <h6 class="media-heading mb-0">{{$delivery_address_details->state }}</h6>
                                                <p class="font-small-2 mb-0 text-muted">{{tr('state')}}</p>
                                            </div>

                                        </div>
                                        
                                    </a>

                                    <a href="javascript:void(0)" class="list-group-item">

                                        <div class="media">
                                      
                                            <div class="media-body w-100">
                                                <h6 class="media-heading mb-0">{{$delivery_address_details->pincode}}</h6>
                                                <p class="font-small-2 mb-0 text-muted">{{tr('pincode')}}</p>
                                            </div>

                                        </div>
                                        
                                    </a>

                                    <a href="javascript:void(0)" class="list-group-item">

                                        <div class="media">
                                      
                                            <div class="media-body w-100">
                                                <h6 class="media-heading mb-0">{{ common_date($delivery_address_details->updated_at,Auth::guard('admin')->user()->timezone) }}</h6>
                                                <p class="font-small-2 mb-0 text-muted">{{tr('updated_at')}}</p>
                                            </div>

                                        </div>
                                        
                                    </a>

                                    <a href="javascript:void(0)" class="list-group-item">

                                        <div class="media">
                                      
                                            <div class="media-body w-100">
                                                <h6 class="media-heading mb-0">{{ common_date($delivery_address_details->created_at,Auth::guard('admin')->user()->timezone) }}</h6>
                                                <p class="font-small-2 mb-0 text-muted">{{tr('created_at')}}</p>
                                            </div>

                                        </div>
                                        
                                    </a>
                                 
                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</section>

@endsection